import type {
  AnimationConfig,
  BackgroundConfig,
  EffectsConfig,
  TextStyle,
  TitleStyle,
  VisualStyleId,
} from './types';
import { SONCEIBE_LOGO_DATA_URL } from './sonceibe-logo-data';

export const SONCEIBE_LOGO_URL = SONCEIBE_LOGO_DATA_URL;

export interface VisualPreset {
  id: Exclude<VisualStyleId, 'default'>;
  label: string;
  description: string;
  previewFrom: string;
  previewTo: string;
  accent: string;
  background: Partial<BackgroundConfig>;
  text: Partial<TextStyle>;
  title: Partial<TitleStyle>;
  animation: Partial<AnimationConfig>;
  effects: Partial<EffectsConfig>;
}

export const visualPresets: VisualPreset[] = [
  {
    id: 'sonceibe',
    label: 'SonCeibe',
    description: 'Verde bosque, ámbar, borde celta y marca Son Ceibe',
    previewFrom: '#102d25',
    previewTo: '#26190f',
    accent: '#d99a45',
    background: {
      type: 'gradient',
      gradientFrom: '#102d25',
      gradientTo: '#26190f',
      gradientAngle: 145,
      overlay: 0.08,
    },
    text: {
      fontFamily: 'Georgia',
      fontSize: 82,
      fontWeight: 700,
      color: '#f4ead7',
      outlineWidth: 2,
      outlineColor: '#17392f',
      shadow: true,
      shadowBlur: 20,
      shadowColor: '#061712',
      glow: true,
      glowColor: '#d99a45',
      glowIntensity: 12,
      position: 'center',
      align: 'center',
      lineHeight: 1.22,
    },
    title: {
      fontFamily: 'Georgia',
      fontSize: 100,
      fontWeight: 800,
      fontStyle: 'normal',
      color: '#f4ead7',
      outlineWidth: 2.5,
      outlineColor: '#17392f',
      shadow: true,
      shadowBlur: 20,
      shadowColor: '#061712',
      glow: true,
      glowColor: '#d99a45',
      glowIntensity: 14,
      topOffset: 18,
      uppercase: true,
    },
    animation: {
      in: 'fade',
      out: 'fade',
      duration: 0.55,
      karaokeColor: '#e7b86d',
    },
    effects: {
      overlay: 0.08,
      overlayColor: '#071811',
      particles: true,
      particlesCount: 18,
      lightleaks: false,
      vignette: true,
      vignetteIntensity: 0.38,
    },
  },
  {
    id: 'rock-galego',
    label: 'Rock Galego',
    description: 'Carbón, metal envejecido, focos ámbar y letras de escenario',
    previewFrom: '#090a0c',
    previewTo: '#32130f',
    accent: '#d46b3c',
    background: {
      type: 'gradient',
      gradientFrom: '#090a0c',
      gradientTo: '#32130f',
      gradientAngle: 155,
      overlay: 0.12,
    },
    text: {
      fontFamily: 'Impact',
      fontSize: 84,
      fontWeight: 800,
      color: '#f4eee5',
      outlineWidth: 3,
      outlineColor: '#110d0b',
      shadow: true,
      shadowBlur: 22,
      shadowColor: '#000000',
      glow: true,
      glowColor: '#d46b3c',
      glowIntensity: 7,
      position: 'center',
      align: 'center',
      transform: 'uppercase',
      letterSpacing: 1.5,
      lineHeight: 1.16,
    },
    title: {
      fontFamily: 'Impact',
      fontSize: 106,
      fontWeight: 900,
      fontStyle: 'normal',
      color: '#f3e9df',
      outlineWidth: 4,
      outlineColor: '#110d0b',
      shadow: true,
      shadowBlur: 24,
      shadowColor: '#000000',
      glow: true,
      glowColor: '#d46b3c',
      glowIntensity: 10,
      topOffset: 18,
      uppercase: true,
    },
    animation: {
      in: 'zoom',
      out: 'fade',
      duration: 0.34,
      karaokeColor: '#e58a55',
      wordStagger: 45,
    },
    effects: {
      overlay: 0.13,
      overlayColor: '#080606',
      particles: true,
      particlesCount: 14,
      lightleaks: true,
      vignette: true,
      vignetteIntensity: 0.5,
      kenburns: false,
    },
  },
  {
    id: 'folk-atlantico',
    label: 'Folk Atlántico',
    description: 'Verdes, océano, bruma y ornamentación orgánica de aire atlántico',
    previewFrom: '#0d302b',
    previewTo: '#345866',
    accent: '#ccb57b',
    background: {
      type: 'gradient',
      gradientFrom: '#0d302b',
      gradientTo: '#345866',
      gradientAngle: 150,
      overlay: 0.09,
    },
    text: {
      fontFamily: 'Georgia',
      fontSize: 78,
      fontWeight: 700,
      color: '#f2ead8',
      outlineWidth: 1.5,
      outlineColor: '#18362f',
      shadow: true,
      shadowBlur: 16,
      shadowColor: '#061816',
      glow: false,
      position: 'center',
      align: 'center',
      transform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.25,
    },
    title: {
      fontFamily: 'Georgia',
      fontSize: 98,
      fontWeight: 700,
      fontStyle: 'italic',
      color: '#f5ecd9',
      outlineWidth: 1.5,
      outlineColor: '#18362f',
      shadow: true,
      shadowBlur: 16,
      shadowColor: '#061816',
      glow: false,
      topOffset: 18,
      uppercase: false,
    },
    animation: {
      in: 'fade',
      out: 'fade',
      duration: 0.72,
      karaokeColor: '#d9c58f',
      wordStagger: 70,
    },
    effects: {
      overlay: 0.08,
      overlayColor: '#061a18',
      particles: true,
      particlesCount: 10,
      lightleaks: false,
      vignette: true,
      vignetteIntensity: 0.3,
      kenburns: true,
      kenburnsIntensity: 0.3,
    },
  },
  {
    id: 'ska-ceibe',
    label: 'Ska Ceibe',
    description: 'Amarelo, verde e negro, damero, diagonais e rebote rítmico',
    previewFrom: '#131713',
    previewTo: '#617424',
    accent: '#f2d24d',
    background: {
      type: 'gradient',
      gradientFrom: '#131713',
      gradientTo: '#617424',
      gradientAngle: 135,
      overlay: 0.08,
    },
    text: {
      fontFamily: 'Impact',
      fontSize: 84,
      fontWeight: 800,
      color: '#fff5c7',
      outlineWidth: 4,
      outlineColor: '#111111',
      shadow: true,
      shadowBlur: 12,
      shadowColor: '#000000',
      glow: false,
      position: 'center',
      align: 'center',
      transform: 'uppercase',
      letterSpacing: 1,
      lineHeight: 1.14,
    },
    title: {
      fontFamily: 'Impact',
      fontSize: 108,
      fontWeight: 900,
      fontStyle: 'normal',
      color: '#f3d44d',
      outlineWidth: 5,
      outlineColor: '#111111',
      shadow: true,
      shadowBlur: 14,
      shadowColor: '#000000',
      glow: false,
      topOffset: 18,
      uppercase: true,
    },
    animation: {
      in: 'bounce',
      out: 'fade',
      duration: 0.36,
      karaokeColor: '#8ecf59',
      wordStagger: 45,
    },
    effects: {
      overlay: 0.06,
      overlayColor: '#10130e',
      particles: true,
      particlesCount: 20,
      lightleaks: false,
      vignette: true,
      vignetteIntensity: 0.22,
      kenburns: false,
    },
  },
  {
    id: 'galicia-gaita',
    label: 'Galicia / Gaita',
    description: 'Azul galego, pedra, vieiras, trisqueles e silueta de gaita',
    previewFrom: '#123251',
    previewTo: '#6f95b5',
    accent: '#dbe9f3',
    background: {
      type: 'gradient',
      gradientFrom: '#123251',
      gradientTo: '#6f95b5',
      gradientAngle: 140,
      overlay: 0.1,
    },
    text: {
      fontFamily: 'Georgia',
      fontSize: 80,
      fontWeight: 700,
      color: '#f4f7f9',
      outlineWidth: 2,
      outlineColor: '#12304c',
      shadow: true,
      shadowBlur: 18,
      shadowColor: '#071827',
      glow: true,
      glowColor: '#9dc6e2',
      glowIntensity: 7,
      position: 'center',
      align: 'center',
      transform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.22,
    },
    title: {
      fontFamily: 'Georgia',
      fontSize: 100,
      fontWeight: 800,
      fontStyle: 'normal',
      color: '#f6f8fa',
      outlineWidth: 2.5,
      outlineColor: '#12304c',
      shadow: true,
      shadowBlur: 18,
      shadowColor: '#071827',
      glow: true,
      glowColor: '#9dc6e2',
      glowIntensity: 9,
      topOffset: 19,
      uppercase: true,
    },
    animation: {
      in: 'slide',
      out: 'fade',
      duration: 0.5,
      karaokeColor: '#c8deec',
      wordStagger: 60,
    },
    effects: {
      overlay: 0.08,
      overlayColor: '#0b2136',
      particles: false,
      lightleaks: false,
      vignette: true,
      vignetteIntensity: 0.32,
      kenburns: true,
      kenburnsIntensity: 0.22,
    },
  },
  {
    id: 'taberna-galega',
    label: 'Taberna Galega',
    description: 'Madeira, pedra, luz quente e ambiente de viño e cantiga',
    previewFrom: '#4a2815',
    previewTo: '#130d09',
    accent: '#d6a052',
    background: {
      type: 'gradient',
      gradientFrom: '#4a2815',
      gradientTo: '#130d09',
      gradientAngle: 165,
      overlay: 0.08,
    },
    text: {
      fontFamily: 'Georgia',
      fontSize: 80,
      fontWeight: 700,
      color: '#f2dfb7',
      outlineWidth: 2,
      outlineColor: '#32190c',
      shadow: true,
      shadowBlur: 20,
      shadowColor: '#080402',
      glow: true,
      glowColor: '#c57b32',
      glowIntensity: 5,
      position: 'center',
      align: 'center',
      transform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.23,
    },
    title: {
      fontFamily: 'Georgia',
      fontSize: 100,
      fontWeight: 800,
      fontStyle: 'normal',
      color: '#f4dcae',
      outlineWidth: 2.5,
      outlineColor: '#32190c',
      shadow: true,
      shadowBlur: 20,
      shadowColor: '#080402',
      glow: true,
      glowColor: '#d28d3f',
      glowIntensity: 8,
      topOffset: 19,
      uppercase: false,
    },
    animation: {
      in: 'fade',
      out: 'fade',
      duration: 0.55,
      karaokeColor: '#e2ad64',
      wordStagger: 65,
    },
    effects: {
      overlay: 0.08,
      overlayColor: '#1b0d06',
      particles: true,
      particlesCount: 12,
      lightleaks: true,
      vignette: true,
      vignetteIntensity: 0.46,
      kenburns: true,
      kenburnsIntensity: 0.18,
    },
  },
];

export function getVisualPreset(id: VisualStyleId | undefined): VisualPreset | null {
  if (!id || id === 'default') return null;
  return visualPresets.find((preset) => preset.id === id) ?? null;
}
